#!/usr/bin/env bash

# load libs
source "$(dirname "$0")/lib/config.sh"
source "$(dirname "$0")/lib/flags.sh"
source "$(dirname "$0")/lib/util.sh"
source "$(dirname "$0")/lib/backend.sh"
source "$(dirname "$0")/lib/map.sh"

# load commands
for cmd in "$(dirname "$0")"/cmds/*.sh; do
  source "$cmd"
done

# resolve command
CMD="$1"
shift

FUNC="${CMD_MAP[$CMD]}"

if ! declare -f "$FUNC" >/dev/null; then
  echo "Unknown command: $CMD"
  exit 1
fi

"$FUNC" "$@"